server:
  port: 9999

spring:

  data:
    redis:
      password: 111111
      host: 192.168.11.100
      port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: admin123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iron.pojo
  configuration:
    map-underscore-to-camel-case: true