server:
  port: 9999

spring:
  # redis 配置
  redis:
    host: 192.168.11.100
    port: 6379
    password: 111111
    # 集群各机的地址
    single:
      addresses:
        - 192.168.11.100:6379
        - 192.168.11.102:6380
        - 192.168.11.103:6381

# mybaits配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iron.dao

logging:
  pattern:
    console: console:%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n
  level:
    root: info