server:
  port: 8888

spring:
  # redis 配置
  redis:
    host: 192.168.11.100
    port: 6379
    password: 111111

  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybaits配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iron.dao

logging:
  pattern:
    console: console:%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n
  level:
    root: info